[atom]
db_url = "postgres://postgres:39f12851f5275222e8b50fddddf04ee4@postgres:5432/aggregator"
prs_base_url = "https://prs-bp[1-3].press.one/api/chain"
bind_address = "0.0.0.0:7070"
thread_num = 50
xml_output_dir = "output"

[[topics]]
name = "prs"
topic = "a06d94c3c6a50c5893f366148bc863dec4d4d676"
encryption_key = "daf786d6738c2b44a3f884f23fcf68db99103128241bcbc0345d1660155c8d5b"
iv_prefix = "5b52d68fefc1f24d4ee8cd8d23dff9a6d21742ff7cd2fcacbd7e8679f41051a2"

[[topics]]
name = "xue"
topic = "b6b17424f87ffb8b5b853291f6dbaf0aac661ca2"
encryption_key = "daf786d6738c2b44a3f884f23fcf68db99103128241bcbc0345d1660155c8d5b"
iv_prefix = "5b52d68fefc1f24d4ee8cd8d23dff9a6d21742ff7cd2fcacbd7e8679f41051a2"

[[topics]]
name = "blog"
topic = "5487cc4a976759368d5ff03808070f5d754df3a9"
encryption_key = "daf786d6738c2b44a3f884f23fcf68db99103128241bcbc0345d1660155c8d5b"
iv_prefix = "5b52d68fefc1f24d4ee8cd8d23dff9a6d21742ff7cd2fcacbd7e8679f41051a2"

[[topics]]
name = "seaky"
topic = "78c762c206c96d00479e503aaa0ee857146160d5"
encryption_key = "0842cfd36769dd2697a2b770389c3b5da7036be63a06297ea4d157a366ece1af"
iv_prefix = "af2560de968e0fac06653d2c099f8fc4ccdd1e7ed07cecca068cb742efba2fb4"